# Generated by Django 4.2.7 on 2024-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucardmaster',
            name='template_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menucardmaster',
            name='template_file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menucardmaster',
            name='template_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menucardmaster',
            name='template_file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='psmmaster',
            name='psm_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sdmmaster',
            name='sdm_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
