# Generated by Django 4.2.7 on 2024-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucardmaster',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menucardmaster',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
