# Generated by Django 4.2.7 on 2023-12-27 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdomaster',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2023, 12, 27)),
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='updated_date',
            field=models.DateTimeField(default=datetime.date(2023, 12, 27)),
        ),
    ]
