# Generated by Django 4.2.7 on 2024-02-27 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomaster',
            name='logo_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='apps/client_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creatormaster',
            name='creator_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customermapping',
            name='csm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.csmmaster'),
        ),
        migrations.AlterField(
            model_name='customermapping',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.industrymaster'),
        ),
        migrations.AlterField(
            model_name='customermapping',
            name='opp_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customermapping',
            name='psm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.psmmaster'),
        ),
        migrations.AlterField(
            model_name='customermapping',
            name='sdm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sdmmaster'),
        ),
        migrations.AlterField(
            model_name='customermapping',
            name='success_elements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.successelementsmaster'),
        ),
        migrations.AlterField(
            model_name='logomaster',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logomaster',
            name='logo_file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='projectid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='psmmaster',
            name='psm_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sdmmaster',
            name='sdm_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
