# Generated by Django 5.0.1 on 2024-01-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcapabilitymaster',
            name='sub_capability_name',
            field=models.CharField(max_length=100),
        ),
    ]
