# Generated by Django 4.2.7 on 2024-03-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logomaster',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_images'),
        ),
    ]
