# Generated by Django 4.2.7 on 2024-03-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_logomaster_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='successreport',
            name='psm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.psmmaster'),
        ),
    ]
