# Generated by Django 5.0.1 on 2024-01-24 18:08

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_menusdomapping_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermapping',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.projectmaster'),
        ),
        migrations.AlterField(
            model_name='customermapping',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.regionmaster'),
        ),
    ]
