# Generated by Django 4.2.7 on 2024-02-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_logomaster_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontactmaster',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.statusmaster'),
        ),
    ]
