# Generated by Django 5.0.1 on 2024-01-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_subcapabilitymaster_sub_capability_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcapabilitymaster',
            name='sub_capability_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
