# Generated by Django 4.2.7 on 2024-01-16 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_menucardmaster_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermapping',
            old_name='csm_id',
            new_name='csm',
        ),
        migrations.RenameField(
            model_name='customermapping',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customermapping',
            old_name='industry_id',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='customermapping',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='customermapping',
            old_name='psm_id',
            new_name='psm',
        ),
        migrations.RenameField(
            model_name='customermapping',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='customermapping',
            old_name='sdm_id',
            new_name='sdm',
        ),
        migrations.RenameField(
            model_name='customermapping',
            old_name='success_elements_id',
            new_name='success_elements',
        ),
        migrations.RenameField(
            model_name='customermapping',
            old_name='success_service_id',
            new_name='success_service',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='capability_id',
            new_name='capability',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='expert_id',
            new_name='expert',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='logo_id',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='menu_card_id',
            new_name='menu_card',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='report_status_id',
            new_name='report_status',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='successreport',
            old_name='sub_capability_id',
            new_name='sub_capability',
        ),
        migrations.AddField(
            model_name='successreport',
            name='parent_key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 16)),
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='updated_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 16)),
        ),
    ]
