# Generated by Django 4.2.7 on 2024-03-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_successreport_psm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_logo', to='dashboard.logomaster'),
        ),
        migrations.AddField(
            model_name='successreport',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
