# Generated by Django 5.0.1 on 2024-01-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_subcapabilitymaster_sub_capability_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatormaster',
            name='creator_account_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='csmmaster',
            name='csm_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='customer_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='expertmaster',
            name='expert_account_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='industrymaster',
            name='industry_type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sdmmaster',
            name='sdm_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='sdo_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
