# Generated by Django 4.2.7 on 2024-02-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customercontactmaster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontactmaster',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.statusmaster'),
        ),
    ]
