# Generated by Django 4.2.7 on 2024-01-03 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_menucardmaster_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capability_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCapabilityMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_capability_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.capabilitymaster')),
            ],
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='MenuCards',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='menucardmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2024, 1, 3)),
        ),
        migrations.AlterField(
            model_name='menucardmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2024, 1, 3)),
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 3)),
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='updated_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 3)),
        ),
    ]
