# Generated by Django 4.2.7 on 2024-01-17 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_csm_id_customermapping_csm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdomaster',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 17)),
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='updated_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 17)),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='parent_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
