# Generated by Django 4.2.7 on 2024-02-19 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_successreport_snow_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successreport',
            name='approved_by_csm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='approved_by_sdm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='approved_by_sdo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='approved_csm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='approved_sdm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='approved_sdo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_report_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.creatormaster'),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customermaster'),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='download_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='error_msg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.logomaster'),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='report_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.reportstatusmaster'),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='snow_case_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.statusmaster'),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='sub_capability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcapabilitymaster'),
        ),
        migrations.AlterField(
            model_name='successreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_report_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
