# Generated by Django 4.2.7 on 2024-01-08 11:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_capabilitymaster_productmaster_subcapabilitymaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermapping',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menucardmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2024, 1, 8)),
        ),
        migrations.AlterField(
            model_name='menucardmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2024, 1, 8)),
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 8)),
        ),
        migrations.AlterField(
            model_name='sdomaster',
            name='updated_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 8)),
        ),
    ]
