# Generated by Django 4.2.7 on 2024-02-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_successreport_approved_by_csm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successreport',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.expertmaster'),
        ),
    ]
