# Generated by Django 5.0.1 on 2024-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_creatormaster_creator_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='projectid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
