# Generated by Django 4.2.7 on 2024-01-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_customermapping_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaster',
            name='project_logo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
