# Generated by Django 5.0.1 on 2024-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_projectmaster_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaster',
            name='projectid',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
