# Generated by Django 4.2.7 on 2024-02-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_successreport_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatormaster',
            name='creator_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expertmaster',
            name='expert_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
