# Generated by Django 4.2.7 on 2024-03-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_customermaster_logo_customermapping_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logomaster',
            name='logo_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
