# Generated by Django 4.2.7 on 2024-01-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_projectmaster_project_logo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customermapping',
            name='updated_by',
        ),
    ]
