# Generated by Django 4.2.7 on 2024-03-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_logomaster_logo_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermapping',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.logomaster'),
        ),
    ]
