# Generated by Django 4.2.7 on 2024-02-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_customercontactmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='successreport',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customercontactmaster'),
        ),
    ]
