# Generated by Django 4.2.7 on 2024-02-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_excustomercontactsmaster_successreport_csm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermaster',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='expertmaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expertmaster',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='expertmaster',
            name='status',
        ),
        migrations.RemoveField(
            model_name='expertmaster',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='expertmaster',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='customercontactmaster',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_created_contacts', to='dashboard.expertmaster'),
        ),
        migrations.AlterField(
            model_name='customercontactmaster',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_updated_contacts', to='dashboard.expertmaster'),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_created', to='dashboard.expertmaster'),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_updated', to='dashboard.expertmaster'),
        ),
        migrations.AlterField(
            model_name='expertmaster',
            name='expert_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expertmaster',
            name='expert_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
